name: AirGame-API
version: ${project.version}
main: net.airgame.bukkit.api.AirGameAPI
api-version: 1.16
load: STARTUP

softdepend:
  - Vault
  - PlayerPointsAPI

authors: [ Hamster3 ]
description: 五彩方块服务器的API系统
website: https://www.airgame.net/