name: AirGame-API
version: ${project.version}
main: net.airgame.bukkit.api.PluginMain
api-version: 1.16
load: STARTUP

authors: [ Hamster3 ]
description: 五彩方块服务器的API系统
website: https://www.airgame.net/